<?php

/**
 * Implements hook_theme().
 */
function accordion_table_theme(array $existing, string $type, string $theme, string $path): array {
  /** @var \Drupal\accordion_table\HookHandlers\ThemeHandler $service */
  $service = \Drupal::service('accordion_table.hook_handlers.theme');

  return $service->execute($existing, $type, $theme, $path);
}

/**
 * Implements hook_preprocess_accordion_table().
 */
function accordion_table_preprocess_accordion_table(array &$variables) {
  /** @var \Drupal\accordion_table\HookHandlers\PreprocessHandlers\PreprocessAccordionTableHandler $service */
  $service = \Drupal::service('accordion_table.hook_handlers.preprocess_accordion_table');

  $service->preprocess($variables);
}

/**
 * Implements hook_preprocess_views_view_accordiontable().
 */
function accordion_table_preprocess_views_view_accordiontable(array &$variables) {
  /** @var \Drupal\accordion_table\HookHandlers\PreprocessHandlers\PreprocessViewsViewAccordionTableHandler $service */
  $service = \Drupal::service('accordion_table.hook_handlers.preprocess_views_view_accordiontable');

  $service->preprocess($variables);
}
