<?php

use Drupal\views\ViewExecutable;

/**
 * Implements template_preprocess_HOOK().
 */
function accordion_table_preprocess_views_view_accordiontable(&$variables) {
  template_preprocess_views_view_table($variables);

  /** @var ViewExecutable $view */
  $view = $variables['view'];
  $options = $view->style_plugin->options;

  $variables['attributes']['class'][] = 'accordion-table';
  if (!empty($options['separate_operations'])) {
    $variables['attributes']['class'][] = 'separate-operations-buttons';
  }
  if (!empty($variables['responsive'])) {
    $variables['attributes']['class'][] = 'responsive';
  }

  $variables['has_result'] = !empty($variables['view']->result);
  if (!empty($variables['has_result'])) {
    $variables['attributes']['class'][] = 'has-result';
  }

  if (!empty($options['table_class'])) {
    $variables['attributes']['class'] = array_merge($variables['attributes']['class'], explode(' ', $options['table_class']));
  }
}
