accordion_table.settings:
  type: config_object
  label: 'Accordion Table settings'
  mapping:
    allow_multiple_open_rows:
      type: boolean
      label: 'Allow multiple open rows'
    priority_breakpoint_mapping:
      type: sequence
      label: 'Mapping information between column priority and theme breakpoint'
      sequence:
        type: mapping
        mapping:
          low:
            type: string
            label: 'Breakpoint for displaying columns with low priority'
          medium:
            type: string
            label: 'Breakpoint for displaying columns with medium priority'
